version: '3.8'

services:
  web:
    build: 
      context: ./src
      dockerfile: dockerfile.prod
    command: gunicorn todo_project.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=susi
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=studentDB
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web